"""Sudoku solver"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/index.ipynb.

# %% auto 0
__all__ = ['board', 'b']

# %% ../nbs/index.ipynb 14
board = ['8-----41-', 
         '-6-9-----', 
         '3-2------', 
         '-5---814-', 
         '4----1--3', 
         '-8---326-', 
         '1-9------', 
         '-7-3-----', 
         '2-----85-']

# %% ../nbs/index.ipynb 16
b = Board(board)
b.solve(False)

# %% ../nbs/index.ipynb 18
b = Board(board)
b.solve(True)
